production:
  daily_sync:
    class: DailySyncJob
    schedule: every day at 6am
  recurring_billing:
    class: RecurringBillingJob
    schedule: every day at 7am
  usage_sync:
    class: UsageSyncJob
    schedule: every day at 6am

development:
  daily_sync:
    class: DailySyncJob
    schedule: every day at 6am
  recurring_billing:
    class: RecurringBillingJob
    schedule: every day at 7am
  usage_sync:
    class: UsageSyncJob
    schedule: every day at 6am
